// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAYbkQjHz635708aYKLp0GEfO-GlmvPCI0',
    appId: '1:171685597188:web:8bbbfc92fbce343f446551',
    messagingSenderId: '171685597188',
    projectId: 'foxus-b2a4b',
    authDomain: 'foxus-b2a4b.firebaseapp.com',
    storageBucket: 'foxus-b2a4b.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAIMmwBm1m68bYBV3ltPUj_aeqj6FCVxdA',
    appId: '1:171685597188:android:a74616684c33a004446551',
    messagingSenderId: '171685597188',
    projectId: 'foxus-b2a4b',
    storageBucket: 'foxus-b2a4b.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCIyKlsjrJ-Qi1i1WXFjvVm-vYH1kL2G-k',
    appId: '1:171685597188:ios:3667ed7ce5204f22446551',
    messagingSenderId: '171685597188',
    projectId: 'foxus-b2a4b',
    storageBucket: 'foxus-b2a4b.firebasestorage.app',
    iosBundleId: 'com.shamsi.foxus',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCIyKlsjrJ-Qi1i1WXFjvVm-vYH1kL2G-k',
    appId: '1:171685597188:ios:3667ed7ce5204f22446551',
    messagingSenderId: '171685597188',
    projectId: 'foxus-b2a4b',
    storageBucket: 'foxus-b2a4b.firebasestorage.app',
    iosBundleId: 'com.shamsi.foxus',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAYbkQjHz635708aYKLp0GEfO-GlmvPCI0',
    appId: '1:171685597188:web:850e4cd2cd277ef0446551',
    messagingSenderId: '171685597188',
    projectId: 'foxus-b2a4b',
    authDomain: 'foxus-b2a4b.firebaseapp.com',
    storageBucket: 'foxus-b2a4b.firebasestorage.app',
  );
}
